# Generated by Django 6.1 on 2026-10-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_relationship_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(condition=models.Q(('user_a_id__lt', models.F('user_b_id'))), name='relationship_user_a_lt_user_b'),
        ),
    ]
