# Generated by Django 6.1 on 2026-10-04 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_relationship_check_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_deleted_by_a', models.BooleanField(default=False)),
                ('chat_deleted_by_b', models.BooleanField(default=False)),
                ('sidebar_hidden_by_a', models.BooleanField(default=False)),
                ('sidebar_hidden_by_b', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversation States',
                'unique_together': {('user_a', 'user_b')},
            },
        ),
    ]
